import {
  Dice6Icon,
  Folder,
  Folders,
  Grid2x2X,
  Grid3x3,
  LayoutGrid,
  ListTodoIcon,
  SignatureIcon,
  SignpostBigIcon,
  Square,
  Star,
  Users2,
} from "lucide-react";

export const uiProblemRoutes = [
  {
    name: "Get Started",
    href: "/ui-problems",
    icon: LayoutGrid,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "Explorer I",
    href: "/ui-problems/explorer-one",
    icon: Folder,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "Explorer II",
    href: "/ui-problems/explorer-two",
    icon: Folders,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "Star Rating",
    href: "/ui-problems/star-rating",
    icon: Star,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "Task Managment",
    href: "/ui-problems/task-managment",
    icon: ListTodoIcon,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "Task Managment - II",
    href: "/ui-problems/task-managment-ii",
    icon: ListTodoIcon,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "Task Managment - III",
    href: "/ui-problems/task-managment-iii",
    icon: ListTodoIcon,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "MC Quiz App",
    href: "/ui-problems/mc-quiz-app",
    icon: Folder,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "OTP Input",
    href: "/ui-problems/otp-input",
    icon: SignatureIcon,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "Tic Tac Toe I",
    href: "/ui-problems/tic-tac-toe",
    icon: Square,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "Tic Tac Toe II",
    href: "/ui-problems/tic-tac-toe-ii",
    icon: Square,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "Tic Tac Toe III",
    href: "/ui-problems/tic-tac-toe-iii",
    icon: Square,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "Dice Roller I",
    href: "/ui-problems/dice-roller-i",
    icon: Dice6Icon,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "Dice Roller II",
    href: "/ui-problems/dice-roller-ii",
    icon: Dice6Icon,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "Dice Roller III",
    href: "/ui-problems/dice-roller-iii",
    icon: Dice6Icon,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "Dice Roller IV",
    href: "/ui-problems/dice-roller-iv",
    icon: Dice6Icon,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "Multi Select",
    href: "/ui-problems/multi-select",
    icon: Dice6Icon,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "User Lists",
    href: "/ui-problems/user-lists",
    icon: Users2,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "Grid Lights",
    href: "/ui-problems/grid-lights",
    icon: Grid3x3,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "Grid Lights II",
    href: "/ui-problems/grid-lights-ii",
    icon: Grid2x2X,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "Grid Lights III",
    href: "/ui-problems/grid-lights-iii",
    icon: Grid2x2X,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "Traffic Light",
    href: "/ui-problems/traffic-light",
    icon: SignpostBigIcon,
    sideDescription: "",
    pageDescription: "",
  },
  {
    name: "Traffic Light - II",
    href: "/ui-problems/traffic-light-ii",
    icon: SignpostBigIcon,
    sideDescription: "",
    pageDescription: "",
  },
];
